### ISSUE TITLE
Some shortcuts won't work

### ISSUE THREAD

**Issue by simaks** [rimas-kudelis/macos-keyboard-layouts#2]
In some applications like web browser there are short cuts like:

- zoom in: cmd + "+" (doesn't work with Lithuanian - Numeric)
- zoom out: cmd + "-" (works)
- zoom reset: cmd + 0 (doesn't work with Lithuanian - Numeric)

Two of these doesn't work.
Some other input sources

On mac Lithuanian input source zooming in is done using shift
![image](https://github.com/rimas-kudelis/macos-keyboard-layouts/assets/5489941/5842cc2d-f3eb-4c02-bb96-8cf460429d17)

**Comment by rimas-kudelis** [comment]
Hi, thank you for the bug report! I have an idea how this could be fixed, now I just have to get to testing it out.

**Comment by rimas-kudelis** [comment]
Yep, the US QWERTY fallback for when Cmd is pressed is exactly what I have in mind.

**Comment by simaks** [comment]
Some combinations like switching browser tab using cmd+1 or cmd+2 is working even with ą and č without fallback.

**Comment by rimas-kudelis** [comment]
> I've been using a modified version of the numeric layout that solves this problem - the idea is to fall back to standard QWERTY layout whenever a modifier key is pressed, as I don't think there's any software that actually uses Cmd+Ž as a hotkey. Never took the time to contribute back though :/
> 
> Here's my modified version: [Lithuanian Numeric Keyboard.bundle.zip](https://github.com/rimas-kudelis/macos-keyboard-layouts/files/14022852/Lithuanian.Numeric.Keyboard.bundle.zip) - extract to `/Library/Keyboard Layouts`.

@oleg-vinted, would you mind provinding a PR with your changes?
